services:
  - type: web
    name: insta-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    plan: free
    region: oregon
    envVars: []